site_name: Portfolio

nav:
  - Home: index.md
  - About me:
    - About me: about-me.md
    - Summer 2026: summer-2026.md
  - Brainstorm: brainstorm.md

theme:
  name: material
  palette:
    # Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Zu Dark Mode wechseln

    # Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Zu Light Mode wechseln

watch:
  - docs

plugins:
   - glightbox
